plugins {
    id 'net.fabricmc.fabric-loom' // Без версии! Она подтянется из settings.gradle
    id 'maven-publish'
}

version = '1.0.0'
group = 'com.example'

base {
    archivesName = 'Trigger-Bot'
}

dependencies {
    minecraft "com.mojang:minecraft:1.21.1"
    mappings "net.fabricmc:yarn:1.21.1+build.2:v2"
    modImplementation "net.fabricmc:fabric-loader:0.16.10"
}

processResources {
    inputs.property "version", project.version
    filteringCharset "UTF-8"
    filesNotMatching("*.png") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release.set(21)
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}"}
    }
}
