pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
    plugins {
        // Объявляем плагин Fabric Loom и его версию прямо здесь
        id 'net.fabricmc.fabric-loom' version '1.7.4'
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        mavenCentral()
    }
}

rootProject.name = 'Trigger-Bot'
